OBSERVED_FILE: "/tmp/cat"
EVENT_ALL_EXEC: "echo 'EVENT_ALL_EXEC'"
EVENT_CREATE_EXEC: "echo 'EVENT_CREATE_EXEC'"
EVENT_WRITE_EXEC: "echo 'EVENT_WRITE_EXEC'"
EVENT_REMOVE_EXEC: "echo 'EVENT_REMOVE_EXEC'"
EVENT_RENAME_EXEC: "echo 'EVENT_RENAME_EXEC'"
EVENT_CHMOD_EXEC: "echo 'EVENT_CHMOD_EXEC'"
